theme="amp"

baseURL = "https://Huny-B.info/"
languageCode = "en-us"
title = "Huny-B.info"

copyright = "Â© 2018 Huny-B CBD-Oil Ltd Co. All Rights Reserved"
canonifyurls = true

[params]
  description = "Huny-B CBD-Oil product information portal." #optional
  googleanalytics = "UA-128206672-2" # optional

# optional
[social]
  twitter = "HunyBcbd"
  #github = "Your Github Name"
  facebook = "HunyBcbd"
  #gplus = "Your Google+ profile name"
  #linkedin = "Your LinkedIn Name"

[taxonomies]
  tag      = "tags"
  category = "categories"
  concern = "concerns"
  ingredient = "ingredients"
  product = "products"
  report = "reports"
  qrcode = "c"