baseURL = "http://SativaDelight.com/"
languageCode = "en-us"
title = "SativaDelight.com"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Service"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Portfolio"
    URL = "portfolio"
    weight = 4

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

    [[menu.nav]]
    name = "Pricing"
    URL = "pricing"
    weight = 6

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
gmapAPI = ""

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "https://res.cloudinary.com/elijahskinner/image/upload/v1541740268/Huny-b/green.png"
    icon = "tf-ion-play"
    heading = "Site Under Construction"
    content= "Live your life pain free!"
    btn = true
    btnText="Explore Us"
    btnURL="#services"

    # call to action
    [params.cta]
    enable = true
    title = "Great Design & Incredible Results"
    content = "Our bath bombs are specifically designed to relieve pain after a long day."
    

    # counter
    [params.counter]
    enable = true
    bgImage = "https://res.cloudinary.com/elijahskinner/image/upload/v1541740494/Huny-b/orange.png"
        [[params.counter.counterItem]]
        title = "Happy Customers"
        icon = "tf-ion-android-happy"
        count = "100%"

        [[params.counter.counterItem]]
        title = "Different Types of Products"
        pre = "<i class=\"fa fa-flask\"></i>"
        count = "27"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "95"

        #[[params.counter.counterItem]]
        #title = "Cups of Coffee"
        #icon = "tf-ion-coffee"
        #count = "2500"
    
    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
		url = "https://www.facebook.com/HunyBcbd/"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
       
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"